name: Setup node and install dependencies
description: A reusable workflow to setup node and install dependencies
inputs:
  node-version:
    description: "NodeJS version to setup"
    required: false
    default: 22
runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/cache@v5
      id: npm-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
