name: Deploy distribution
#on: [push, workflow_dispatch]
on:
  - push
  - workflow_dispatch
#on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test project
        uses: actions/checkout@v6
      - name: Setup NodeJS
        id: setup-nodejs
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: actions/cache@v5
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Check node version
        run: node -v
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Test code
        run: npm run test
      - name: Completed job
        run: echo "Test job was completed"
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v6
      - name: Setup NodeJS
        id: setup-nodejs
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: actions/cache@v5
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Check node version
        run: node -v
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build code
        run: npm run build
      - name: Completed job
        run: echo "Build job was completed"
  deploy:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        run: echo "Deploying project to npm registry"
