name: Deploy distribution
#on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - README.md
      - .github/workflows/*
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test project
        uses: actions/checkout@v6
      - name: Setup Node and install dependencies
        uses: ./.github/actions/setupnode
        with:
          node-version: 20
      - name: Test code
        run: npm run test
      - name: Completed job
        run: echo "Test job was completed"
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v6
      - name: Setup Node and install dependencies
        uses: ./.github/actions/setupnode
      - name: Build code
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
      - name: Completed job
        run: echo "Build job was completed"
  deploy:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist-files
          path: dist
      - name: Deploy project
        run: |
          echo "Deploying files below"
          ls -la dist
          echo "Deployment completed"
